Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2018-05, with the labels that each got.

#85 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#87 [Changelog] Update for Sprint 85
  CHANGELOG.md
Labels: documentation

#92 Inventory Enterprise (Nuage) into CloudTenant (MIQ)
  app/models/manageiq/providers/nuage/inventory/collector.rb
  app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
  app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
  app/models/manageiq/providers/nuage/inventory/persister/network_manager.rb
  app/models/manageiq/providers/nuage/inventory/persister/target_collection.rb
  app/models/manageiq/providers/nuage/inventory_collection_default/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_tenant.rb
  app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
  app/models/manageiq/providers/nuage/network_manager/network_group.rb
  spec/factories/cloud_tenant.rb
  spec/factories/network_group.rb
  spec/models/manageiq/providers/nuage/network_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/inventory_parser_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_tenant.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_tenant_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_tenant_is_updated.yml
Labels: inventory, refactoring

#90 Drop legacy refresh parser
  app/models/manageiq/providers/nuage/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager/refresh_parser.rb
  app/models/manageiq/providers/nuage/network_manager/refresher.rb
Labels: enhancement, gaprindashvili/no
