Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2018-03, with the labels that each got.

#68 Handle subnets with missing gateway/netmask
  app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
Labels: bug, gaprindashvili/yes

#70 Fix Nuage specs using have_attributes
  spec/models/manageiq/providers/nuage/network_manager_spec.rb
Labels: test

#69 Don't run EventCatcher when user opts-in for "None"
  app/models/manageiq/providers/nuage/network_manager/event_catcher.rb
  spec/factories/ext_management_system.rb
  spec/models/manageiq/providers/nuage/network_manager/event_catcher_spec.rb
Labels: enhancement, gaprindashvili/yes

#73 Also connect to CNAAlarms AMQP topic
  config/settings.yml
Labels: enhancement, gaprindashvili/yes

#75 [Changelog] Update for Sprint 81
  CHANGELOG.md
Labels: documentation

#79 [Changelog] Update for Sprint 82
  CHANGELOG.md
Labels: documentation

#78 Don't raise exceptions from within AMQP callbacks
  app/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler.rb
  app/models/manageiq/providers/nuage/network_manager/event_catcher/stream.rb
  spec/models/manageiq/providers/nuage/network_manager_spec.rb
Labels: enhancement, gaprindashvili/yes
