Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2018-10, with the labels that each got.

#150 Cross-connect NetworkPorts by `vm.uid_ems`
  app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
  app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_vm.yml
Labels: enhancement, hammer/yes

#151 [HAMMER] Update i18n catalog for hammer
  locale/ManageIQ_Providers_Nuage.pot
  locale/en/ManageIQ_Providers_Nuage.po
  locale/es/ManageIQ_Providers_Nuage.po
  locale/fr/ManageIQ_Providers_Nuage.po
  locale/ja/ManageIQ_Providers_Nuage.po
  locale/pt_BR/ManageIQ_Providers_Nuage.po
  locale/zh_CN/ManageIQ_Providers_Nuage.po
  zanata.xml
Labels: internationalization

#153 Travis - change postgres to 9.5
  .travis.yml
Labels: gaprindashvili/yes, hammer/yes

#154 Raise error when built-in CRUD playbook fails
  app/models/manageiq/providers/nuage/ansible_crud_mixin.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb
  app/models/manageiq/providers/nuage/network_manager/floating_ip.rb
  app/models/manageiq/providers/nuage/network_manager/security_group.rb
  spec/models/manageiq/providers/nuage/network_manager/cloud_subnet_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/floating_ip_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/security_group_spec.rb
  spec/spec_helper.rb
Labels: enhancement, hammer/yes
