Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2018-06, with the labels that each got.

#88 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: test

#95 [Changelog] Update for Gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#94 Inventory L2 Domain entity (Nuage) as CloudSubnet model (MIQ)
  app/models/manageiq/providers/nuage/inventory/collector.rb
  app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
  app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet_l2.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet_l3.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_tenant.rb
  app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml
Labels: enhancement

#96 [Changelog] Update for Sprint 87
  CHANGELOG.md
Labels: documentation

#99 Reset API headers after each call
  app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
  app/models/manageiq/providers/nuage/network_manager/vsd_client/rest.rb
  spec/models/manageiq/providers/nuage/vsd_client/vsd_client_spec.rb
Labels: enhancement

#89 Cleanup config/settings.yaml after changes in UI
  config/settings.yml
Labels: enhancement, gaprindashvili/no
