Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2018-09, with the labels that each got.

#142 Moving Inventory Builder functionality to Inventory
  app/models/manageiq/providers/nuage/builder.rb
  app/models/manageiq/providers/nuage/inventory.rb
Labels: refactoring

#143 Improve coverage: event catcher and custom toolbar
  spec/helpers/manageiq/providers/nuage/toolbar_overrides/network_router_center_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/events/alarm_4713.json
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/events/alarm_create.json
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/events/alarm_delete.json
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/events/domain_create.json
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/events/enterprise_create.json
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/events/policygroup_create.json
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/events/subnet_create.json
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/runner_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/stream_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_parser_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_target_parser_spec.rb
Labels: test

#144 Cleanup refresher code
  app/models/manageiq/providers/nuage/inventory/collector.rb
  app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
Labels: cleanup

#146 Add running of common core provider specs
  lib/tasks_private/spec.rake
Labels: test

#147 [GAPRINDASHVILI] Prevent crash upon inventoring SecurityGroups
  app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
Labels: bug
