Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2018-07, with the labels that each got.

#101 Inventory vPort entities (Nuage) into NetworkPort model (MIQ)
  app/models/manageiq/providers/nuage/inventory/collector.rb
  app/models/manageiq/providers/nuage/inventory/collector/network_manager.rb
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
  app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
  app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb
  app/models/manageiq/providers/nuage/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager/network_port/bridge.rb
  app/models/manageiq/providers/nuage/network_manager/network_port/container.rb
  app/models/manageiq/providers/nuage/network_manager/network_port/host.rb
  app/models/manageiq/providers/nuage/network_manager/network_port/vm.rb
  app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml
Labels: enhancement

#102 Temporarily remove many-to-many from NetworkRouter
  app/models/manageiq/providers/nuage/network_manager/network_router.rb
Labels: enhancement

#105 Properly subclass CloudSubnet
  app/models/manageiq/providers/nuage/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet/l2.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet/l3.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet_l2.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet_l3.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
Labels: enhancement

#107 Narrow down focus of targeted refresh
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_subnet.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_subnet_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_subnet_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_tenant.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_tenant_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_tenant_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/security_group.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/security_group_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/security_group_is_updated.yml
Labels: enhancement

#109 Targeted refresh for L2 and L3 CloudSubnets
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
  app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
  app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
  spec/factories/cloud_subnet.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/l2_cloud_subnet.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/l2_cloud_subnet_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/l2_cloud_subnet_is_updated.yml
Labels: enhancement

#110 Targeted refresh for FloatingIp
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
  app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
  app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
  spec/factories/floating_ip.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/floating_ip.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/floating_ip_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/floating_ip_is_updated.yml
Labels: enhancement

#111 Targeted refresh for NetworkPorts
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
  app/models/manageiq/providers/nuage/network_manager/event_target_parser.rb
  app/models/manageiq/providers/nuage/network_manager/vsd_client.rb
  spec/factories/network_port.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_bridge.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_container.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_host.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_vm.yml
Labels: enhancement

#112 Reduce memoization in targeted refresh
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
Labels: enhancement

#113 Relate FloatingIp to NetworkRouter
  app/models/manageiq/providers/nuage/inventory/parser/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager/network_router.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
Labels: enhancement

#114 Infer related CloudSubnet in case of NetworkPort refresh
  app/models/manageiq/providers/nuage/inventory/collector/target_collection.rb
  app/models/manageiq/providers/nuage/inventory/persister/definitions/network_collections.rb
Labels: enhancement

#116 Check for invalid api_version string
  app/models/manageiq/providers/nuage/manager_mixin.rb
  app/models/manageiq/providers/nuage/network_manager/vsd_client/rest.rb
  spec/models/manageiq/providers/nuage/network_manager_spec.rb
Labels: enhancement

#115 Destroy dependent entities when parent is deleted
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_tenant.rb
  app/models/manageiq/providers/nuage/network_manager/network_router.rb
  spec/factories/network_router.rb
  spec/models/manageiq/providers/nuage/network_manager/cloud_tenant_spec.rb
Labels: enhancement

#117 Implement CREATE operation for CloudSubnet
  app/models/manageiq/providers/nuage/ansible_crud_mixin.rb
  app/models/manageiq/providers/nuage/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb
  content_tmp/ansible/create-subnet.yml
  content_tmp/ansible/roles/requirements.yml
  spec/models/manageiq/providers/nuage/network_manager/cloud_subnet_spec.rb
Labels: unmergeable

#120 [Changelog] Update for Sprint 91
  CHANGELOG.md
Labels: documentation
