Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2019-01, with the labels that each got.

#162 Change FactoryGirl to FactoryBot
  spec/factories/cloud_network.rb
  spec/factories/cloud_subnet.rb
  spec/factories/cloud_tenant.rb
  spec/factories/ext_management_system.rb
  spec/factories/floating_ip.rb
  spec/factories/network_port.rb
  spec/factories/network_router.rb
  spec/factories/security_group.rb
  spec/models/manageiq/providers/nuage/network_manager/cloud_subnet_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/cloud_tenant_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/runner_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_catcher_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_parser_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_target_parser_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/floating_ip_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/security_group_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/refresher_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/vcr_specs/targeted_refresh_spec.rb
  spec/models/manageiq/providers/nuage/network_manager_spec.rb
Labels: gaprindashvili/no, hammer/no

#163 Remove duplicated persister shared_options
  app/models/manageiq/providers/nuage/inventory/persister.rb
Labels: hammer/yes, refactoring

#164 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation
