Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2019-07, with the labels that each got.

#173 [HAMMER] Bump hammer travis.yml to ruby 2.4.6
  .travis.yml
Labels: test

#178 Add a rubocop channel to the codeclimate config
  .codeclimate.yml
Labels: dependencies

#180 [IVANCHUK] yarn: lock versions by adding yarn.lock
  .gitignore
  yarn.lock
Labels: dependencies

#184 Update the excludes block in .travis.yml
  .travis.yml
Labels: ivanchuk/no, test

#183 Update the excludes block in .travis.yml
  spec/other/travis_spec.rb
Labels: ivanchuk/yes, test
