Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2020-09, with the labels that each got.

#222 Fix nuage VCRs for rest-client 2.1.0
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_network_floating.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_network_floating_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_network_floating_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_subnet.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_subnet_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_subnet_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_tenant.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_tenant_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/cloud_tenant_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/floating_ip.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/floating_ip_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/floating_ip_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/l2_cloud_subnet.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/l2_cloud_subnet_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/l2_cloud_subnet_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_bridge.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_container.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_host.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_port_vm.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_router.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_router_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/network_router_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/security_group.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/security_group_is_deleted.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/refresher_targeted/security_group_is_updated.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/domain.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/domains.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/domains_for_enterprise_id.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/enterprise.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/enterprises.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/login.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/policy_group.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/policy_groups.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/policy_groups_for_domain.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/subnet.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/subnets.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/subnets_for_domain.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/vms.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/wrong_pass.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/wrong_user.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/zone.yml
  spec/vcr_cassettes/manageiq/providers/nuage/network_manager/vsd_client/zones.yml
Labels: test

#223 Fixed JS syntax error in the create cloud subnet form
  app/javascript/components/create-nuage-cloud-subnet-form.jsx
Labels: bug

#224 Plugin Generator Updates
  .codeclimate.yml
  .gitignore
  .rubocop.yml
  .rubocop_cc.yml
  .travis.yml
  README.md
  Rakefile
  bin/ci/after_script
  bundler.d/.keep
  lib/manageiq/providers/nuage/engine.rb
  lib/tasks/README.md
  lib/tasks_private/spec.rake
  lib/tasks_private/yarn.rake
  manageiq-providers-nuage.gemspec
  spec/spec_helper.rb
  spec/support/playbook_helper.rb
Labels: developer

#221 [JANSA] yarn upgrade: upgrade JS dependencies
  package.json
  yarn.lock
Labels: dependencies, jansa/yes

#225 Make the default credentials required in the provider DDF
  app/models/manageiq/providers/nuage/manager_mixin.rb
Labels: bug

#226 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/nuage/manager_mixin.rb
Labels: enhancement
