Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2020-04, with the labels that each got.

#203 Update the qpid-proton C library version to 0.30.0
  .gitignore
  tools/ci/before_install.sh
Labels: dependencies

#206 Use :payload instead of :data, set :proxy, in Rest class
  app/models/manageiq/providers/nuage/network_manager/vsd_client/rest.rb
Labels: bug

#208 Use before_install to setup bundle_with qpid_proton
  tools/ci/before_install.sh
Labels: test
