Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2020-05, with the labels that each got.

#211 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#212 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#210 Convert the Cloud Subnet Form to DDF and get rid of react-ui-components
  .travis.yml
  Rakefile
  app/javascript/components/create-nuage-cloud-subnet-form.jsx
  app/javascript/components/create-nuage-cloud-subnet-form.schema.js
  app/javascript/components/forms/nuage-cloud-subnet-form.jsx
  app/javascript/utils/api.js
  app/javascript/utils/validators.js
  package.json
  spec/javascript/components/__snapshots__/create-nuage-cloud-subnet-form.test.jsx.snap
  spec/javascript/components/create-nuage-cloud-subnet-form.test.jsx
  spec/javascript/components/forms/__snapshots__/nuage-cloud-subnet-form.test.jsx.snap
  spec/javascript/components/forms/nuage-cloud-subnet-form.test.jsx
  spec/javascript/setup.js
  spec/javascript/utils/api.test.js
  spec/other/travis_spec.rb
Labels: cleanup
