Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2021-03, with the labels that each got.

#243 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#240 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-nuage_network_manager_event_catcher.target
  build/systemd_units/manageiq-providers-nuage_network_manager_event_catcher@.service
  build/systemd_units/manageiq-providers-nuage_network_manager_refresh.target
  build/systemd_units/manageiq-providers-nuage_network_manager_refresh@.service
Labels: technical debt

#241 Implemented DDF for cloud subnets and added support mixin call
  app/models/manageiq/providers/nuage/network_manager.rb
  app/models/manageiq/providers/nuage/network_manager/cloud_subnet.rb
Labels: enhancement
