Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2022-02, with the labels that each got.

#265 Remove Hakiri
  README.md
Labels: cleanup, developer

#266 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-nuage.gemspec
  tools/ci/before_install.sh
Labels: developer, test

#267 Restore deleted before_install
  .github/workflows/ci.yaml
  bin/before_install
Labels: developer, test

#268 Add Build History Graph to README.md
  README.md
Labels: developer, test

#269 Replace deprecated method .parent in rails 6.1
  spec/models/manageiq/providers/nuage/vsd_client/vcr_specs/vsd_client_spec.rb
Labels: cleanup, rails6.1

#263 Update node version
  package.json
Labels: dependencies

#270 Downgrade node version to 14
  package.json
Labels: dependencies

#271 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
