Repository ManageIQ/manageiq-providers-nuage, pull requests merged in 2023-10, with the labels that each got.

#298 Fix xlab-si galaxy roles pointing to invalid repository URL
  content/ansible_runner/create-subnet.yml
  content/ansible_runner/remove-floating-ip.yml
  content/ansible_runner/remove-policy-group.yml
  content/ansible_runner/remove-subnet.yml
  content/ansible_runner/roles/requirements.yml
Labels: bug

#299 Require the gem defining the constant we're subclassing
  app/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler.rb
  lib/manageiq/providers/nuage/engine.rb
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/messaging_handler_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/runner_spec.rb
  spec/models/manageiq/providers/nuage/network_manager/event_catcher/stream_spec.rb
  spec/models/manageiq/providers/nuage/network_manager_spec.rb
  spec/spec_helper.rb
Labels: bug, rails7

#301 Drop Ruby 2.7
  .github/workflows/ci.yaml
Labels: dependencies
